baseURL: 'https://www.moonheart.dev'
languageCode: 'zh-cn'
title: '月心月士的博客'
paginate: 5
theme: "PaperMod"

outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
params:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  assets:
    disableHLJS: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  author: moonheart
  homeInfoParams:
    Title: Hello
    Content: 搞机新手 | 音游菜鸟 | 程序猿
  ShowReadingTime: true
  editPost:
    URL: "https://github.com/moonheart/moonheart.github.io/blob/master/content"
    Text: "发现错误？" # edit text
    appendFilePath: true # to append file path to Edit link
  socialIcons:
    - name: github
      url: "https://github.com/moonheart"
menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: About
      url: about/
      weight: 11
      
